import Link from "next/link";
import { Download, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/shell";
import { audit, readStore } from "@/lib/store";
import { requireUser } from "@/lib/auth";

export const metadata = {
  robots: {
    index: false,
    follow: false
  }
};

export default async function ReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const user = await requireUser();
  const store = await readStore();
  const report = store.reports.find((candidate) => candidate.id === id && (candidate.userId === user.id || user.role === "admin"));
  if (!report) return null;
  await audit("view_report", "report", report.id, user.id);
  const snapshot = report.snapshot;

  return (
    <AppShell>
      <main className="mx-auto max-w-5xl px-4 py-8">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <p className="text-sm uppercase tracking-[0.18em] text-brass">Verification {report.verificationCode}</p>
            <h1 className="mt-3 text-3xl font-semibold text-vellum">{snapshot.title}</h1>
            <p className="mt-2 text-vellum/62">Generated {new Date(report.generatedAt).toLocaleString()}</p>
          </div>
          <Link className="inline-flex h-11 items-center gap-2 rounded bg-brass px-4 font-semibold text-ink" href={`/reports/${report.id}/pdf`}>
            <Download className="h-4 w-4" />
            Download PDF
          </Link>
        </div>
        <section className="paper-panel mt-6 rounded-lg p-6">
          <h2 className="text-xl font-semibold text-vellum">{snapshot.propertyAddress}</h2>
          <div className="mt-5 h-72 rounded border border-vellum/10 bg-charcoal subtle-grid">
            <div className="grid h-full place-items-center text-center text-vellum/55">
              <div>
                <p className="text-sm uppercase tracking-[0.2em] text-brass">Map snapshot</p>
                <p className="mt-2">Centered at {snapshot.mapCenter.join(", ")}</p>
                {snapshot.radiusMeters ? <p>Radius: {snapshot.radiusMeters}m</p> : null}
              </div>
            </div>
          </div>
          <div className="mt-6 grid gap-4">
            {snapshot.incidents.length ? (
              snapshot.incidents.map((incident, index) => (
                <article key={`${incident.sourceUrl}-${index}`} className="rounded border border-vellum/10 p-4">
                  <p className="text-sm text-brass">{incident.category} · {incident.incidentYear}</p>
                  <h3 className="mt-2 text-lg font-semibold text-vellum">{incident.title}</h3>
                  <p className="mt-2 text-vellum/68">{incident.publicSummary}</p>
                  <p className="mt-3 text-sm text-vellum/62">
                    Source:{" "}
                    <a className="text-brass" href={incident.sourceUrl} target="_blank" rel="noreferrer">
                      {incident.sourceTitle}
                    </a>
                  </p>
                </article>
              ))
            ) : (
              <p className="rounded border border-vellum/10 p-4 text-vellum/65">
                No sourced incident found in Property Chronicle records at the time of report generation.
              </p>
            )}
          </div>
          <div className="mt-6 rounded border border-brass/30 bg-brass/10 p-4 text-sm leading-6 text-vellum/72">
            <div className="flex gap-2">
              <ShieldCheck className="mt-0.5 h-4 w-4 text-brass" />
              <p>
                This report organizes publicly sourced information and does not determine legal disclosure obligations.
                Use responsibly, verify through listed sources, and do not use this information for harassment,
                trespass, unlawful discrimination, or contacting occupants.
              </p>
            </div>
          </div>
          <p className="mt-6 text-center text-sm text-vellum/45">Generated by Property Chronicle</p>
        </section>
      </main>
    </AppShell>
  );
}
