import { NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { audit, mutateStore, readStore } from "@/lib/store";

export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const user = await getCurrentUser();
  if (!user) return new NextResponse("Unauthorized", { status: 401 });
  const store = await readStore();
  const report = store.reports.find((candidate) => candidate.id === id && (candidate.userId === user.id || user.role === "admin"));
  if (!report) return new NextResponse("Not found", { status: 404 });
  await mutateStore((draft) => {
    const target = draft.reports.find((candidate) => candidate.id === report.id);
    if (target) target.downloadedAt = new Date().toISOString();
  });
  await audit("download_report_pdf", "report", report.id, user.id);
  const lines = [
    report.snapshot.title,
    `Verification: ${report.verificationCode}`,
    `Generated: ${report.generatedAt}`,
    `Property: ${report.snapshot.propertyAddress}`,
    "",
    ...report.snapshot.incidents.flatMap((incident) => [
      `${incident.category} (${incident.incidentYear}) - ${incident.title}`,
      incident.publicSummary,
      `Source: ${incident.sourceTitle} - ${incident.sourceUrl}`,
      ""
    ]),
    "This report organizes publicly sourced information and does not determine legal disclosure obligations.",
    "Generated by Property Chronicle"
  ];
  const body = makePdf(lines);

  return new NextResponse(body, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${report.verificationCode}.pdf"`
    }
  });
}

function makePdf(lines: string[]) {
  const safeLines = lines.flatMap((line) => wrap(line, 92));
  const textCommands = safeLines
    .slice(0, 54)
    .map((line, index) => `1 0 0 1 54 ${742 - index * 13} Tm (${escapePdf(line)}) Tj`)
    .join("\n");
  const stream = `BT\n/F1 10 Tf\n${textCommands}\nET`;
  const objects = [
    "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
    "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n",
    "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
    `5 0 obj\n<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream\nendobj\n`
  ];
  let offset = "%PDF-1.4\n".length;
  const xref = objects.map((object) => {
    const current = offset;
    offset += Buffer.byteLength(object);
    return current;
  });
  const content = `%PDF-1.4\n${objects.join("")}xref\n0 6\n0000000000 65535 f \n${xref
    .map((entry) => `${String(entry).padStart(10, "0")} 00000 n `)
    .join("\n")}\ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${offset}\n%%EOF`;
  return content;
}

function escapePdf(value: string) {
  return value.replaceAll("\\", "\\\\").replaceAll("(", "\\(").replaceAll(")", "\\)").replace(/[^\x20-\x7E]/g, "-");
}

function wrap(value: string, width: number) {
  if (!value) return [""];
  const words = value.split(/\s+/);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    if (`${current} ${word}`.trim().length > width) {
      lines.push(current);
      current = word;
    } else {
      current = `${current} ${word}`.trim();
    }
  }
  lines.push(current);
  return lines;
}
